addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.2")
addSbtPlugin("io.h8.sbt" %% "sbt-dependencies" % "1.1.1")
addSbtPlugin("io.h8.sbt" % "sbt-scoverage-summary" % "1.0.6")
addSbtPlugin("io.h8.sbt" % "sbt-testkit" % "2.0.2")
