addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.6.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.12.0")
addSbtPlugin("com.github.sbt" % "sbt-unidoc" % "0.6.1")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.8.7")
addSbtPlugin("io.h8.sbt" %% "sbt-dependencies" % "1.1.1")
addSbtPlugin("io.h8.sbt" % "sbt-scoverage-summary" % "2.0.0")
addSbtPlugin("io.h8.sbt" % "sbt-testkit" % "2.2.0")
